name: Deploy Live Editor
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node_modules-build-deploy-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-deploy-

      - name: Build & Deploy
        run: |
          npm i -g yarn
          export DEPLOY=true
          export BETA=true
          echo "$GITHUB_EVENT_NAME"
          rm -rf docs/_app
          yarn install
          # yarn run lint
          version=$(yarn version --patch --no-git-tag-version | grep "New version" | cut -d':' -f 2)
          yarn build
          cd bin
          ./fix-path
          cd ..
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -nm "Release $version"
          git push
