name: Deploy Live Editor
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Deploy
        run: |
          npm i -g yarn
          yarn install
          yarn run lint
          version=$(yarn version --patch --no-git-tag-version | grep "New version" | cut -d':' -f 2)
          export CI=true
          yarn build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release $version"
          git push
