name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for all PRs to master and develop.
  pull_request:
    branches:
      - master
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        if: github.ref_type == 'tag'
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          # this will generate tags in the following format:
          #
          # latest
          # 1.2.3
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v5
        if: github.ref_type == 'tag'
        with:
          context: .
          target: mermaid
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/metadata-action@v5
        if: github.ref_type == 'branch'
        id: meta-nightly
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=nightly
      - uses: docker/build-push-action@v5
        if: github.ref_type == 'branch'
        with:
          context: .
          target: mermaid
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          tags: ${{ steps.meta-nightly.outputs.tags }}
          labels: ${{ steps.meta-nightly.outputs.labels }}
