name: Create release pull request
on:
  push:
    branches:
      - develop
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: develop
